//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using System;
using UnityEngine;
using System.Collections;

public class Util
{
	public static IEnumerator SetTimeout(float seconds, Action  onComplete)
	{
		yield return new WaitForSeconds(seconds);
		onComplete();
	}

	public static void SetTimeout(Action  onComplete,float seconds){
		Log.StartCoroutine(SetTimeout(seconds, onComplete));
	}


}

